config/routes.rb
Rails.application.routes.draw do
  get 'links/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :links
  resources :views, path: :v, only: :show
  root "links#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
  has_many :views, dependent: :destroy

  scope :recent_first, -> { order(created_at: :desc)}

  validates :url, presence: true

  def self.find(id)
    super  ShortCode.decode(id)
  end

  def to_param
    ShortCode.encode(id)
  end

  def domain
    URI(url).host rescue URI::InvalidURIError
  end
end

app/models/short_code.rb
class ShortCode
  ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".freeze
  BASE = ALPHABET.length

  def self.encode(number)
    return ALPHABET.first if number.zero? || number.nil?

    result = ""

    while number > 0 do
      index = number % BASE
      char = ALPHABET[index]
      result.prepend char
      number = number / BASE
    end

    result
  end

  def self.decode(string)
    number = 0
    string.reverse.each_char.with_index do |char, index|
      power = BASE**index
      index = ALPHABET.index(char)
      number += index * power
    end
    number
  end
end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :link, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   def set_link
    @link = Link.find(params[:id])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  def index
    @links = Link.recent_first
    @link ||= Link.new
  end

  def show
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      redirect_to root_path
    else
      @links = Link.recent_first
      render :index, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
    if @link.update(link_params)
      redirect_to @link
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @link.destroy
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def link_params
    params.require(:link).permit(:url)
  end
end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
  before_action :set_link, only: :show

  rescue_from ActiveRecord::RecordNotFound do
    redirect_to root_path, notice: "Missing Link !"
  end

  def show
    @link.views.create(ip: request.ip, user_agent: request.user_agent)
    redirect_to @link.url, allow_other_host: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="prose mx-auto mt-28 px-5">
      <%= tag.p notice, class: "bg-blue-100 text-blue-800 text-small font-medium px-4 py-2 rounded" if notice %>
      <%= tag.p alert, class: "bg-red-100 text-black-800 text-small font-medium px-4 py-2 rounded" if alert%>
      <%= yield %>
    </main>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with model: link do |f| %>
  <div class="flex gap-2 items-center">
    <%= f.url_field :url, placeholder: "https://example.org/", required: true, autofocus: true, class: "flex-grow rounded" %>
    <%= f.button "Save", class: "px-3 py-2 bg-gray-100 rounded" %>
  </div>
<% end %>

app/views/links/_link.html.erb
<%= tag.div id: dom_id(link) do %>
  <div class="grid grid-cols-8 items-center py-4">
    <div class="col-span-5 ">
      <%= link_to view_path(link), target: :_blank, data: {turbo: false}, class: "no-underline" do  %>
        <%= image_tag "https://www.google.com/s2/favicons?domain=#{link.domain}", class: "inline-block" %>
        <%= link.url %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 inline-block">
          <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
        </svg>
      <% end %>
    </div>
    <div class="col-span-2 text-center text-xs">
      <%= link_to pluralize(link.views_count, "view"), link, class: "px-2 py-2 rounded bg-gray-100 no-underline" %>
    </div>
    <div class="text-center text-xs">
      <%= link_to "Copy", link, class: "px-2 py-2 rounded bg-gray-100 no-underline" %>
    </div>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Edit Link</h1>

<%= render partial: "form", locals: { link: @link }%>

<div class="flex gap-1 items-center mt-4">
  <%= link_to "Cancel", @link %> 
  or
  <%= button_to "Delete", @link, method: :delete, data: {turbo_confirm: "Are u sure ?"} %></div>

app/views/links/index.html.erb
<div>
  <h1 class="font-bold text-4xl">URL Shortener</h1>
  
  <%= render partial: "form", locals: {link: @link} %>
  
  <div class="mt-8 flex-col divide-y divide-gray-10">
    <%= render @links %>
  </div>
</div>

app/views/links/show.html.erb
<div class="flex justify-between items-center text-xs">
  <%= link_to "← Back to all links", root_path, class: "no-underline text-xs px-3 py-2 rounded bg-gray-100" %>
  <div class="flex items-center gap-4">
    <%= tag.div pluralize(@link.views_count, "view") %>
    <%= link_to "Edit", edit_link_path(@link), class: "px-2 py-2 rounded bg-gray-100 no-underline" %>
  </div>
</div>

<h1 class="mt-4"><%= @link.url %></h1>
<%= @link.description %>

<%= link_to view_path(@link), target: :_blank, data: {turbo: false}, class: "text-xs px-2 py-2 rounded bg-gray-100 no-underline"  do  %>
  <%= image_tag "https://www.google.com/s2/favicons?domain=#{@link.domain}", class: "inline-block" %>

  <%= @link.url %>
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 inline-block">
    <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
  </svg>
<% end %>
<%= line_chart @link.views.group_by_day(:created_at, range: 2.weeks.ago..Time.current, expand_range: true).count %>